#!/bin/sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# Follow this guide whrn updating yabai to latest version
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#updating-to-the-latest-release

# global settings
yabai -m config window_border on
yabai -m config window_border_width        1
yabai -m config window_border_radius       8
yabai -m config active_window_border_color 0xFFFFFFFF
yabai -m config normal_window_border_color 0x00FFFFFF
yabai -m config insert_feedback_color 0xFFA3BE8C

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config mouse_drop_action            stack
yabai -m config window_shadow                float
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0             
yabai -m config normal_window_opacity        1.0
yabai -m config window_opacity_duration      0.0
yabai -m config window_border_blur off

# general space settings
yabai -m config external_bar                 all:35:20
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   7

yabai -m config insert_feedback_color        0xffd65d0e

# Unmanaged apps
app_titles="(Copy|Bin|About This Mac|Info|Finder Preferences|Preferences"
app_titles+="|QuickTime Player|Stickies)"
yabai -m rule --add title="${app_titles}" manage=off

app_names="^(Calculator|Authy Desktop|Postgres|VLC|System Preferences|IINA"
app_names+="|iMazing HEIC Converter|AppCleaner|Stickies|1Password 7|VeraCrypt"
app_names+="|Tunnelblick|WireGuard|Logi Options|JetBrains Toolbox"
app_names+="|Logi Options\+)$"
yabai -m rule --add app="${app_names}" manage=off

# Tries to focus the window under the cursor whenever the MS teams notification gains focus
# Probably conflicts with mouse follows focus in some ways
yabai -m signal --add \
    event=window_focused \
    app='^Microsoft Teams$' \
    title='^Microsoft Teams Notification$' \
    
    action='yabai -m window --focus next > /dev/null 2>&1'

# Don't manage WhatsApp call windows
yabai -m signal --add \
    event=window_focused \
    app='^WhatsApp$' \
    title='^$' \
    action='yabai -m window --focus next > /dev/null 2>&1'

#Rename spaces[8]
yabai -m space 1 --label main
yabai -m space 2 --label howto
yabai -m space 3 --label fixit
yabai -m space 4 --label others
yabai -m space 5 --label messages
yabai -m space 6 --label research
yabai -m space 7 --label more
yabai -m space 8 --label personal
# yabai -m space --balance
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"nibar-spaces-jsx\"'"

# if using multple displays, add an additional rule for "display_changed" event
yabai -m signal --add event=display_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"nibar-spaces-jsx\"'"

# add these rules to auto-update the "windows" widget
yabai -m signal --add event=window_focused \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"nibar-windows-jsx\"'"
yabai -m signal --add event=window_destroyed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"nibar-windows-jsx\"'"
yabai -m signal --add event=window_created \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"nibar-windows-jsx\"'"
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"nibar-windows-jsx\"'"

    
# Focus window under cursor when an application is hidden
# yabai -m signal --add event=application_hidden \
#     action="yabai -m window --focus mouse"

# Focus window under cursor when a window is destroyed
# yabai -m signal --add event=window_destroyed \
#     action="yabai -m window --focus mouse"

# Focus window under cursor when an application is terminated
# yabai -m signal --add event=application_terminated \
#     action="yabai -m window --focus mouse"

# Rearrange windows when a new display is added
# yabai -m signal --add event=display_added \
#     action="$HOME/.config/yabai/rearrange.sh add"

# Rearrange windows when a display is removed
# yabai -m signal --add event=display_removed \
#     action="$HOME/.config/yabai/rearrange.sh remove"
